### ISSUE TITLE
Proposal: support string interpolation in River

### ISSUE THREAD

**Issue by rfratto** [grafana/river#15]
I'd like to see support for string interpolation added to River. 

String interpolation is a quality-of-life feature which will make it easier to write expressions which return a string. 

For example, this expression:

```river 
env("POD_NAMESPACE") + "/" + env("POD_NAME")
```

could be replaced with the following interpolated string:

```river 
"${env("POD_NAMESPACE")}/${env("POD_NAME")}" 
```

## Syntax 

String interpolation is initiated by placing `${EXPR}` into a string. String interpolation can be escaped by escaping the dollar sign: `\${EXPR}` returns the literal string `${EXPR}`. 

This syntax matches the string interpolation syntax used by HCL.

The parser must keep track of pairs of curly braces to ensure that parsing the inner string does not end early; `${{a=5}}` should be parsed as the expression `{a=5}` and not `{a=5`.  

## Evaluation 

Each EXPR instead of `${EXPR}` will be evaluated, converted to a string, and injected into the resulting output. 

For example:

```river 
"3 + 5 is ${3 + 5}" 
```

evaluates to `"3 + 5 is 8"`. 

Each expression in an interpolated string should be converted into a string form which best represents that value. The representation for types should match the form of that value written in River. Functions and capsules should be converted to some description of the type of the function or capsule, similar to the description which displays in the UI.

## Considerations 

This would be a breaking change for users who are using some form of `${EXPR}` in their configuration files already. I'm not sure if any of our existing Flow components would lead to someone using `${EXPR}` inside of a string. 

If this is going to be an issue, we can change the syntax used to denote a string that supports interpolation, such as any of the following:

* C#-like: `$"3 + 5 is {3 + 5}"`
* Javascript-like: `` `3 + 5 is ${3 + 5}` ``

**Comment by ptodev** [comment]
I think it might be better to have a special `format()` function if string interpolation is required:
```
format("string with {}, and {var2}", var1)
```

This has a few advantages over `${}`:

- Variables/expressions can be specified at the end of the function, leaving the initial string looking cleaner.
- No breaking changes to River.
- A `format` function could also be enhanced to use [printf decorators](https://pkg.go.dev/fmt#hdr-Printing) like `%.2f`.

Disclaimer: my suggestion is inspired by [Rust's format macro](https://doc.rust-lang.org/std/macro.format.html) :) 

Btw PowerShell also uses the `${}` syntax for variables. But it also has `$()`, which is used for expressions. [This post](https://stackoverflow.com/questions/60323111/powershell-string-interpolation-syntax) on StackOverflow explains it in more detail.

**Comment by ptodev** [comment]
@erikbaranowski pointed out to me that we already have a [format function](https://grafana.com/docs/agent/latest/flow/reference/stdlib/format/). I'd personally be in favour of adding a string interpolation feature to it, similar to what was described in the [comment above](https://github.com/grafana/river/issues/15#issuecomment-1731088299).

**Comment by rfratto** [comment]
I'm going to close this for now; it's not clear how necessary this is, especially given the format function exists in the stdlib. We can return to this in the future with a more fleshed out proposal if string interpolation is required.
