### ISSUE TITLE
Missing ',' in expression list

### ISSUE THREAD

**Issue by BruceWouaigne** [grafana/river#40]
Hey good folks, there seems to be a compatibility issue between the river syntax and the HCL (or Helm?) one when it comes to multiline expression on maps (and maybe lists?).

Here's some context.

I am using Terraform with the Helm provider to spin up the grafana-agent in flow mode. 

Here's the content of the `main.tf` file which is in a Terraform module

```
terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
    }
  }
}

locals {
  namespace = "monitoring"
}

resource "kubernetes_namespace" "monitoring_ns" {
  metadata {
    name = local.namespace
  }
}

resource "helm_release" "grafana_agent" {
  name        = "grafana-agent"
  repository  = "https://grafana.github.io/helm-charts"
  chart       = "grafana-agent"
  namespace   = local.namespace

  set {
    name = "agent.configMap.content"
    value = file("${path.module}/config.river")
  }
}
```

And the content of the `config.river` file

```
logging {
	level  = "info"
	format = "logfmt"
}

discovery.kubernetes "pods" {
	role = "pod"
}

discovery.kubernetes "nodes" {
	role = "node"
}

discovery.kubernetes "services" {
	role = "service"
}

discovery.kubernetes "endpoints" {
	role = "endpoints"
}

discovery.kubernetes "endpointslices" {
	role = "endpointslice"
}

discovery.kubernetes "ingresses" {
	role = "ingress"
}

prometheus.remote_write "default" {
  endpoint {
    url = "xxxxxxxx"
    headers = { 
      "X-Token" = "xxxxxxx",
    }
  }
}
```

When trying to `terraform apply` I'm getting the following error: 

```
╷
│ Error: failed parsing key "agent.configMap.content" with value logging {
│       level  = "info"
│       format = "logfmt"
│ }
│
│ discovery.kubernetes "pods" {
│       role = "pod"
│ }
│
│ discovery.kubernetes "nodes" {
│       role = "node"
│ }
│
│ discovery.kubernetes "services" {
│       role = "service"
│ }
│
│ discovery.kubernetes "endpoints" {
│       role = "endpoints"
│ }
│
│ discovery.kubernetes "endpointslices" {
│       role = "endpointslice"
│ }
│
│ discovery.kubernetes "ingresses" {
│       role = "ingress"
│ }
│
│ prometheus.remote_write "default" {
│   endpoint {
│     url = "xxxxxxxx"
│     headers = {
│       "X-Token" = "xxxxxxxx",
│     }
│   }
│ }, key "\n    }\n  }\n}" has no value
│
│   with module.monitoring.helm_release.grafana_agent,
│   on apps/monitoring/main.tf line 19, in resource "helm_release" "grafana_agent":
│   19: resource "helm_release" "grafana_agent" {
```

If I remove the comma at the end of the map value line, `terraform apply` passes but the agent fails to start: `"missing ',' in expression list"`.

I've worked around this by setting the header on a single line (`headers = { "X-Token" = "xxxxxxxx" }`), but I thought I'd let you know in case there is something to fix or if I'm not doing something right.

**Comment by tpaschalis** [comment]
This is a limitation of the `--set` flag that the terraform provider passes [eg. here](https://helm.sh/docs/intro/using_helm/) 

To set the configuration, it's a better practice to use the `--set-file` and pass the file location; you should use the equivalent functionality that the terraform provider allows.

**Comment by tpaschalis** [comment]
Hey @BruceWouaigne apologies for the belated response.

This is a limitation of the `--set` flag that the terraform provider passes [eg. here](https://helm.sh/docs/intro/using_helm/) 

To set the configuration, it's a better practice to use the `--set-file` and pass the file location; you should use the equivalent functionality that the terraform provider allows.

**Comment by BruceWouaigne** [comment]
Sweet, good to know. Thanks!
