### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by rfratto** [grafana/river#9]
The bulk of the documentation for how to use River right now is hosted in the Grafana Agent docs:

* [Documentation for River](https://grafana.com/docs/agent/latest/flow/config-language/)
* [Documentation for standard library](https://grafana.com/docs/agent/latest/flow/reference/stdlib/)

We should have basic documentation here so it's more discoverable, but the source of truth (for Grafana Agent users) won't change.

**Comment by clayton-cornell** [comment]
We could write all River-specific documentation here and mount it in the Agent docs. One source, more than one entry point.

**Comment by rfratto** [comment]
Closing as this is no longer relevant with the move to the Alloy configuration syntax.
